### ISSUE TITLE
Transfer() is used instead of Call() to transfer ETH

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-05-rubicon-findings#123]
# Lines of code

https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L356
https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L374
https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L434
https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L451
https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L491
https://github.com/code-423n4/2022-05-rubicon/blob/8c312a63a91193c6a192a9aab44ff980fbfd7741/contracts/RubiconRouter.sol#L548

# Vulnerability details

## Proof-of-Concept

The use of .transfer() or .send() to send ether is now considered bad practice as gas costs can change, which would break the code. 

The transaction will fail inevitably when:

- Target smart contract does not implement a payable function.
- Target smart contract does implement a payable fallback which uses more than 2300 gas unit.
- Target smart contract implements a payable fallback function that needs less than 2300 gas units but is called through proxy, raising the call’s gas usage above 2300.

## Recommended Mitigation Steps

Use call instead of transfer to send ether. And return value must be checked if sending ether is successful or not. make sure to check for reentrancy.

## Reference

https://github.com/code-423n4/2022-02-redacted-cartel-findings/issues/51
